//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Return
    {
        public long BorrowId { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public long LibrarianId { get; set; }
    
        public virtual Borrow Borrow { get; set; }
        public virtual Librarian Librarian { get; set; }
    }
}
